url: http://wwww.openfpc.org/
baseurl: http://www.openfpc.org

# Site settings
title: OpenFPC
email: your-email@domain.com
description: "Full Packet Captre, open source, easy and on your own hardware"
image:
  head: back_green_256.jpg
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/openfpc
  - title: github
    url: http://github.com/leonward/openfpc
  - title: comments
    url: https://lists.sourceforge.net/lists/listinfo/openfpc-users

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

install:
  step1:
    title: "Get your platform ready"
    body: "OpenFPC is developed on the current Ubuntu LTS (long term support) release; It should function on many other platforms, however your mileage may vary. Get in touch with feedback!"
    image: "img/ubuntu_svg.png"
  step2:
    title: "Get OpenFPC"
    body: "If you're using Ubuntu LTS, either download and install the packages dpkg, or add the apt repository and 'apt-get install openfpc'. Details of how to do this are available in the <a href='https://github.com/leonward/OpenFPC/blob/master/docs/INSTALL'> INSTALL </a>file. However if you want to live on the edge where you'll find different bugs, you're also welcome to <a href='http://github.com/leonward/openfpc'> clone the repo</a>"
    image: "img/ofpc_git_sq.png" 
  step3:
    title: "Install OpenFPC"
    body: "Installing the Ubuntu packages using dpkg or apt-get should leave you with a functioning system. For other platforms check out the shell script openfpc-install included in the tarball, you'll find that it will do most of the installation work for you." 
    image: "img/ofpc_screen_1.png" 
  step4:
    title: "Configure the system"
    body: "After installation you can tweak the settings in openfpc-default.conf. Start and stop all components with the openfpc command. Make sure you check out the usage <a href='https://github.com/leonward/OpenFPC/tree/master/docs'> documentation </a>" 
    image: "img/ofpc_config.png" 
